apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: healthcheck-deployment
spec:
  selector:
    matchLabels:
      app: healthcheck
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: healthcheck
    spec:
      containers:
      - name: healthcheck
        image: mkubik/healthcheck:0.0.1-SNAPSHOT
        ports:
        - containerPort: 3333